### ISSUE TITLE
howto: do observables?

### ISSUE THREAD

**Issue by qaisjp** [qaisjp/community-issues#1]
this (with accessing `data` directly in template)

```typescript
export class HomeComponent implements OnInit {
  data?: Homepage = null;

  constructor(
    private resources: ResourceService,
    private http: HttpClient,
    private log: LogService,
    private alerts: AlertService,
  ) {

  }

  ngOnInit() {
    const url = `${environment.api.baseurl}/private/homepage`;
    this.http.get(url, {headers: {'X-Authorization-None': ''}}).pipe(
      take(1),
      tap(data => this.log.debug(`getHomepage response`, data)),
      catchError((err: HttpErrorResponse) => {
        this.alerts.setAlert(err.message);
        return NEVER;
      }),
      map(data => data as Homepage),
    ).subscribe(data => {
      this.data = data;
    });
  }

}
```

vs. this (with accessing via `(data | async)` in template)

```typescript
export class HomeComponent implements OnInit {
  data: Observable<Homepage>;

  constructor(
    private resources: ResourceService,
    private http: HttpClient,
    private log: LogService,
    private alerts: AlertService,
  ) {

  }

  ngOnInit() {
    const url = `${environment.api.baseurl}/private/homepage`;
    this.data = this.http.get(url, {headers: {'X-Authorization-None': ''}}).pipe(
      take(1),
      tap(data => this.log.debug(`getHomepage response`, data)),
      catchError((err: HttpErrorResponse) => {
        this.alerts.setAlert(err.message);
        return NEVER;
      }),
      map(data => data as Homepage),
    );
  }

}
```

----

Yes, the http request is in the wrong place. This will be moved elsewhere later.

**Comment by Citizen01** [comment]
Even though both should work (maybe the template complains about the nil value for the 1st version and maybe a warning of changed during lifecycle ?), I prefer the latter.
I've seen the second version used in angular modules a lot.

Also you can type the get/post/etc so it will cast the data for you:
```ts
this.http.get<Homepage>(url, {headers: {'X-Authorization-None': ''}})
```
so you don't need `map(data => data as Homepage)` at the end.

**Comment by qaisjp** [comment]
Thanks! I'll keep to using observables like this, then.

> complains about the nil value

It is wrapped in an `*ngIf="data"`.

> so you don't need `map(data => data as Homepage)` at the end.

Fantastic!!!

----

When using observables in this way, I've run into some more tricky scenarios involving nested routes. But I'm not using a resolver for _that_ specific family of routes, so my problems there might just be resolved by writing idiomatic code. 

I'll reopen this if I have similar questions (which can't be answered by a Google search). Thank you again!!!
